language: node_js

node_js: 
  - node

install:
  - npm install

script:   
  - npm run build

deploy:
  provider: npm
  email: gitborlando@gmail.com
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    all_branches: true


